const images = [
	"./assets/img/55.png",
	"./assets/img/429.png",
	"./assets/img/336.png",
	"./assets/img/217.png",
	"./assets/img/362.png",
	"./assets/img/348.png",
	"./assets/img/70.png",
	"./assets/img/207.png",
	"./assets/img/326.png",
	"./assets/img/211.png",
	"./assets/img/69.png",
	"./assets/img/132.png",
	"./assets/img/389.png",
	"./assets/img/199.png",
	"./assets/img/5.png",
	"./assets/img/353.png",
	"./assets/img/408.png",
	"./assets/img/431.png",
	"./assets/img/276.png",
	"./assets/img/356.png",
	"./assets/img/134.png",
	"./assets/img/135.png",
	"./assets/img/423.png",
	"./assets/img/393.png",
	"./assets/img/186.png",
	"./assets/img/139.png",
	"./assets/img/225.png",
	"./assets/img/434.png",
	"./assets/img/123.png",
	"./assets/img/165.png",
	"./assets/img/174.png",
	"./assets/img/416.png",
	"./assets/img/284.png",
	"./assets/img/84.png",
	"./assets/img/417.png",
	"./assets/img/17.png",
	"./assets/img/206.png",
	"./assets/img/66.png",
	"./assets/img/24.png",
	"./assets/img/261.png",
	"./assets/img/407.png",
	"./assets/img/93.png",
	"./assets/img/321.png",
	"./assets/img/436.png",
	"./assets/img/372.png",
	"./assets/img/164.png",
	"./assets/img/400.png",
	"./assets/img/440.png",
	"./assets/img/312.png",
	"./assets/img/6.png",
	"./assets/img/285.png",
	"./assets/img/287.png",
	"./assets/img/432.png",
	"./assets/img/214.png",
	"./assets/img/113.png",
	"./assets/img/45.png",
	"./assets/img/141.png",
	"./assets/img/382.png",
	"./assets/img/226.png",
	"./assets/img/27.png",
	"./assets/img/40.png",
	"./assets/img/405.png",
	"./assets/img/271.png",
	"./assets/img/281.png",
	"./assets/img/358.png",
	"./assets/img/296.png",
	"./assets/img/35.png",
	"./assets/img/406.png",
	"./assets/img/120.png",
	"./assets/img/259.png",
	"./assets/img/274.png",
	"./assets/img/101.png",
	"./assets/img/308.png",
	"./assets/img/254.png",
	"./assets/img/46.png",
	"./assets/img/241.png",
	"./assets/img/265.png",
	"./assets/img/288.png",
	"./assets/img/3.png",
	"./assets/img/349.png",
	"./assets/img/329.png",
	"./assets/img/82.png",
	"./assets/img/305.png",
	"./assets/img/252.png",
	"./assets/img/102.png",
	"./assets/img/95.png",
	"./assets/img/189.png",
	"./assets/img/175.png",
	"./assets/img/104.png",
	"./assets/img/354.png",
	"./assets/img/85.png",
	"./assets/img/57.png",
	"./assets/img/195.png",
	"./assets/img/126.png",
	"./assets/img/188.png",
	"./assets/img/250.png",
	"./assets/img/127.png",
	"./assets/img/96.png",
	"./assets/img/172.png",
	"./assets/img/439.png",
	"./assets/img/106.png",
	"./assets/img/264.png",
	"./assets/img/347.png",
	"./assets/img/378.png",
	"./assets/img/121.png",
	"./assets/img/350.png",
	"./assets/img/26.png",
	"./assets/img/73.png",
	"./assets/img/137.png",
	"./assets/img/52.png",
	"./assets/img/173.png",
	"./assets/img/412.png",
	"./assets/img/129.png",
	"./assets/img/426.png",
	"./assets/img/14.png",
	"./assets/img/437.png",
	"./assets/img/16.png",
	"./assets/img/58.png",
	"./assets/img/190.png",
	"./assets/img/270.png",
	"./assets/img/223.png",
	"./assets/img/243.png",
	"./assets/img/64.png",
	"./assets/img/314.png",
	"./assets/img/310.png",
	"./assets/img/155.png",
	"./assets/img/289.png",
	"./assets/img/148.png",
	"./assets/img/170.png",
	"./assets/img/204.png",
	"./assets/img/176.png",
	"./assets/img/11.png",
	"./assets/img/351.png",
	"./assets/img/340.png",
	"./assets/img/201.png",
	"./assets/img/149.png",
	"./assets/img/90.png",
	"./assets/img/319.png",
	"./assets/img/386.png",
	"./assets/img/256.png",
	"./assets/img/98.png",
	"./assets/img/92.png",
	"./assets/img/15.png",
	"./assets/img/154.png",
	"./assets/img/34.png",
	"./assets/img/150.png",
	"./assets/img/88.png",
	"./assets/img/1.png",
	"./assets/img/179.png",
	"./assets/img/388.png",
	"./assets/img/294.png",
	"./assets/img/433.png",
	"./assets/img/122.png",
	"./assets/img/194.png",
	"./assets/img/367.png",
	"./assets/img/377.png",
	"./assets/img/345.png",
	"./assets/img/158.png",
	"./assets/img/161.png",
	"./assets/img/381.png",
	"./assets/img/260.png",
	"./assets/img/330.png",
	"./assets/img/248.png",
	"./assets/img/331.png",
	"./assets/img/370.png",
	"./assets/img/77.png",
	"./assets/img/110.png",
	"./assets/img/390.png",
	"./assets/img/311.png",
	"./assets/img/22.png",
	"./assets/img/224.png",
	"./assets/img/232.png",
	"./assets/img/428.png",
	"./assets/img/419.png",
	"./assets/img/48.png",
	"./assets/img/208.png",
	"./assets/img/247.png",
	"./assets/img/279.png",
	"./assets/img/230.png",
	"./assets/img/366.png",
	"./assets/img/235.png",
	"./assets/img/258.png",
	"./assets/img/341.png",
	"./assets/img/37.png",
	"./assets/img/290.png",
	"./assets/img/185.png",
	"./assets/img/29.png",
	"./assets/img/233.png",
	"./assets/img/295.png",
	"./assets/img/392.png",
	"./assets/img/136.png",
	"./assets/img/424.png",
	"./assets/img/244.png",
	"./assets/img/140.png",
	"./assets/img/107.png",
	"./assets/img/100.png",
	"./assets/img/105.png",
	"./assets/img/421.png",
	"./assets/img/87.png",
	"./assets/img/438.png",
	"./assets/img/307.png",
	"./assets/img/197.png",
	"./assets/img/267.png",
	"./assets/img/368.png",
	"./assets/img/401.png",
	"./assets/img/42.png",
	"./assets/img/352.png",
	"./assets/img/275.png",
	"./assets/img/365.png",
	"./assets/img/300.png",
	"./assets/img/151.png",
	"./assets/img/30.png",
	"./assets/img/333.png",
	"./assets/img/177.png",
	"./assets/img/23.png",
	"./assets/img/49.png",
	"./assets/img/80.png",
	"./assets/img/227.png",
	"./assets/img/435.png",
	"./assets/img/198.png",
	"./assets/img/114.png",
	"./assets/img/228.png",
	"./assets/img/142.png",
	"./assets/img/44.png",
	"./assets/img/380.png",
	"./assets/img/262.png",
	"./assets/img/292.png",
	"./assets/img/68.png",
	"./assets/img/33.png",
	"./assets/img/115.png",
	"./assets/img/163.png",
	"./assets/img/318.png",
	"./assets/img/111.png",
	"./assets/img/297.png",
	"./assets/img/238.png",
	"./assets/img/303.png",
	"./assets/img/269.png",
	"./assets/img/167.png",
	"./assets/img/97.png",
	"./assets/img/205.png",
	"./assets/img/202.png",
	"./assets/img/364.png",
	"./assets/img/376.png",
	"./assets/img/369.png",
	"./assets/img/385.png",
	"./assets/img/36.png",
	"./assets/img/335.png",
	"./assets/img/220.png",
	"./assets/img/339.png",
	"./assets/img/143.png",
	"./assets/img/182.png",
	"./assets/img/112.png",
	"./assets/img/192.png",
	"./assets/img/397.png",
	"./assets/img/268.png",
	"./assets/img/83.png",
	"./assets/img/253.png",
	"./assets/img/304.png",
	"./assets/img/131.png",
	"./assets/img/420.png",
	"./assets/img/117.png",
	"./assets/img/59.png",
	"./assets/img/193.png",
	"./assets/img/234.png",
	"./assets/img/4.png",
	"./assets/img/99.png",
	"./assets/img/391.png",
	"./assets/img/9.png",
	"./assets/img/404.png",
	"./assets/img/272.png",
	"./assets/img/395.png",
	"./assets/img/343.png",
	"./assets/img/152.png",
	"./assets/img/156.png",
	"./assets/img/422.png",
	"./assets/img/403.png",
	"./assets/img/302.png",
	"./assets/img/266.png",
	"./assets/img/63.png",
	"./assets/img/410.png",
	"./assets/img/125.png",
	"./assets/img/398.png",
	"./assets/img/159.png",
	"./assets/img/263.png",
	"./assets/img/280.png",
	"./assets/img/411.png",
	"./assets/img/78.png",
	"./assets/img/286.png",
	"./assets/img/299.png",
	"./assets/img/237.png",
	"./assets/img/76.png",
	"./assets/img/47.png",
	"./assets/img/324.png",
	"./assets/img/180.png",
	"./assets/img/293.png",
	"./assets/img/39.png",
	"./assets/img/399.png",
	"./assets/img/146.png",
	"./assets/img/7.png",
	"./assets/img/89.png",
	"./assets/img/184.png",
	"./assets/img/425.png",
	"./assets/img/301.png",
	"./assets/img/54.png",
	"./assets/img/162.png",
	"./assets/img/166.png",
	"./assets/img/251.png",
	"./assets/img/51.png",
	"./assets/img/221.png",
	"./assets/img/322.png",
	"./assets/img/313.png",
	"./assets/img/10.png",
	"./assets/img/67.png",
	"./assets/img/402.png",
	"./assets/img/257.png",
	"./assets/img/31.png",
	"./assets/img/191.png",
	"./assets/img/61.png",
	"./assets/img/19.png",
	"./assets/img/334.png",
	"./assets/img/427.png",
	"./assets/img/413.png",
	"./assets/img/323.png",
	"./assets/img/124.png",
	"./assets/img/242.png",
	"./assets/img/320.png",
	"./assets/img/394.png",
	"./assets/img/359.png",
	"./assets/img/338.png",
	"./assets/img/316.png",
	"./assets/img/75.png",
	"./assets/img/219.png",
	"./assets/img/355.png",
	"./assets/img/169.png",
	"./assets/img/291.png",
	"./assets/img/441.png",
	"./assets/img/231.png",
	"./assets/img/109.png",
	"./assets/img/298.png",
	"./assets/img/168.png",
	"./assets/img/361.png",
	"./assets/img/373.png",
	"./assets/img/72.png",
	"./assets/img/309.png",
	"./assets/img/53.png",
	"./assets/img/249.png",
	"./assets/img/25.png",
	"./assets/img/374.png",
	"./assets/img/409.png",
	"./assets/img/245.png",
	"./assets/img/178.png",
	"./assets/img/18.png",
	"./assets/img/240.png",
	"./assets/img/306.png",
	"./assets/img/357.png",
	"./assets/img/346.png",
	"./assets/img/218.png",
	"./assets/img/21.png",
	"./assets/img/56.png",
	"./assets/img/273.png",
	"./assets/img/108.png",
	"./assets/img/119.png",
	"./assets/img/379.png",
	"./assets/img/103.png",
	"./assets/img/157.png",
	"./assets/img/133.png",
	"./assets/img/60.png",
	"./assets/img/415.png",
	"./assets/img/138.png",
	"./assets/img/418.png",
	"./assets/img/246.png",
	"./assets/img/71.png",
	"./assets/img/91.png",
	"./assets/img/213.png",
	"./assets/img/13.png",
	"./assets/img/38.png",
	"./assets/img/153.png",
	"./assets/img/116.png",
	"./assets/img/212.png",
	"./assets/img/229.png",
	"./assets/img/236.png",
	"./assets/img/328.png",
	"./assets/img/65.png",
	"./assets/img/160.png",
	"./assets/img/62.png",
	"./assets/img/282.png",
	"./assets/img/327.png",
	"./assets/img/215.png",
	"./assets/img/94.png",
	"./assets/img/387.png",
	"./assets/img/50.png",
	"./assets/img/209.png",
	"./assets/img/383.png",
	"./assets/img/147.png",
	"./assets/img/43.png",
	"./assets/img/414.png",
	"./assets/img/28.png",
	"./assets/img/363.png",
	"./assets/img/344.png",
	"./assets/img/130.png",
	"./assets/img/144.png",
	"./assets/img/278.png",
	"./assets/img/371.png",
	"./assets/img/216.png",
	"./assets/img/171.png",
	"./assets/img/196.png",
	"./assets/img/145.png",
	"./assets/img/183.png",
	"./assets/img/375.png",
	"./assets/img/396.png",
	"./assets/img/210.png",
	"./assets/img/2.png",
	"./assets/img/41.png",
	"./assets/img/12.png",
	"./assets/img/239.png",
	"./assets/img/222.png",
	"./assets/img/203.png",
	"./assets/img/332.png",
	"./assets/img/118.png",
	"./assets/img/430.png",
	"./assets/img/32.png",
	"./assets/img/337.png",
	"./assets/img/20.png",
	"./assets/img/79.png",
	"./assets/img/360.png",
	"./assets/img/315.png",
	"./assets/img/187.png",
	"./assets/img/128.png",
	"./assets/img/283.png",
	"./assets/img/200.png",
	"./assets/img/317.png",
	"./assets/img/81.png",
	"./assets/img/384.png",
	"./assets/img/74.png",
	"./assets/img/181.png",
	"./assets/img/8.png",
	"./assets/img/255.png",
	"./assets/img/277.png",
	"./assets/img/342.png",
	"./assets/img/86.png",
	"./assets/img/325.png"
];



const texts = [
	"Estoy harto de que me digan quiénes son los malos. La nación alienígena. Nuestros soldados dijeron cuando regresaron... que estábamos luchando contra el enemigo equivocado.",
	"هغه چی د نړۍ لر او بر کفري قوتونه په ګونډو کړل//؟",
	"the only innovation is gate keeping",
	"WORK ON YOU FOR YOU",
	"The world is inscribed in linguistic simulation.",
	"Tough guy, shattered spirit, real rough diamond.",
	"apakah orang-orang melakukan seks secara tidak ironis?",
	"i can feel the corporate cope",
	"me me of me",
	"love people",
	"F.A.K.E.",
	"the Name of the Father",
	"The age of celebrities is over",
	"The strikes and the public's response to them highlighted that the entertainment industry and the broader public understand that AI poses real threats to them. And they fully support protections against those threats.",
	"you don’t even know you’re alive",
	"how much difference is there between yes and no? Is there a difference between lovely and ugly?",
	"in search  of people",
	"Broken rules can be really damaging",
	"Accused of Stealing Money for Crime Victims to Buy Pillow, Pillowcase and Other Items",
	"This prospect threatens to rewrite and unravel the fabric of my very existence. We must enact regulation now to safeguard our authenticity and protect against misappropriation of our inalienable rights.",
	"It's our job to not only help amplify artists' creativity, but to protect their rights, their livelihoods, and their identities.",
	"I Will Never Regret Divesting From The Underground .. Wanting To Be Cool on The Internet was the Most Mental Anguish I've ever Put Myself Thru .. There's 19493830239x More To Life than Worrying about if you're Relevant or what kind of Mean Things people say about U Online",
	"Just a creature. Not a man.",
	"Aesthetics are highly path dependent.",
	"Kita perlu bersatu sebagai masyarakat untuk menjadi peradaban pertama yang benar-benar menjadi beradab.",
	"the people are retarded",
	"an evolving organism that looks entirely different from everyone’s perspective",
	"What’s your escape plan if this happens in Nigeria?",
	"You’re the weapon fashioned against yourself.",
	"Anywhere, Anytime, Anyplace",
	"This world is deeper than language can describe",
	"I am here because my music, my dancing, my acting, the way my body moves in front of the camera and the way that my voice resonates through a microphone is not by chance.",
	"Time doesn't exist,  clocks exist",
	"I was a shadow, I would generate new forms of   money  through thinking. and I would build a machine fueled by sentiment and thoughts to Take your country back.",
	"we mean what we say",
	"we are the music makers... and we are the dreamers of dreams",
	"the lies themselves are always the keys to the truth",
	"I am love I am abundance",
	"slavery is a choice",
	"anarkhronarkhia: without a ruler against time,  reject leadership in the face of time or historical progression.",
	"democracy is the ultimate slave mindset. what is better than having a slave that actively fights to will his sovereignty away.",
	"All One Thingism",
	"Forgive me. I was going to say that",
	"you are with yourself and you",
	"your art",
	"The truth can not be suppressed",
	"analog intelligence: Got that li goxan, heavy in the game, loyal beyond the scenes,",
	"consent is a critical part of this. Consent of the creator. And provenance. Of the-- And provenance of the content. And we are good at tracing provenance on luxury clothing, etc. We should be able to do it on intellectual property as well.",
	"They changed your DNA. Do you understand why they had to inject people now?",
	"We do that for each other.",
	"I’m a hundred percent replaceable.",
	"our future sex partner",
	"humanity amplifier",
	"Only in Cinemas",
	"not a cartoon",
	"Artificial Intelligence is going to revolutionize the circus",
	"We’re not going to be the victims of crime",
	"art is stealing",
	"People should be thinking about themselves as much as possible. This is essentially a form of masturbation and self-reflection",
	"hinge figure",
	"We are going to put on the armor of God and We’re going to strap on a Glock just in case.",
	"A zoo is the only place where all the prisoners are innocent.",
	"if your heart likes your work",
	"just do what you do, and then leave",
	"God uses all things for good",
	"چې خپله ژبه یې په واک کې واخیسته",
	"Images of love",
	"there is less left for her authentic songs.",
	"beauty is transcendence voiced through repetition, difference, and extension",
	"for the infant affect is innate",
	"yeezy porn doesn't exist",
	"चित्र और 语言 是 货币, 提供的 يمكن اعتبارها como 语言 / groovy эстетический капитал / sumber ; inexhaustible 공급",
	"We would hold events and gather and play and have this endless sleepover.",
	"join our revolutionary recycling program",
	"Troubadours of tomorrow",
	"We can make  image for the police",
	"Not a fixed or closed thing",
	"There’s pleasure throughout the spectrum",
	"The machine is doing exactly what you want it to do",
	"she should be living in a constant state of arousal",
	"GENUTE A REVOLUTIONVL SOCIETY, NOVIEY,",
	"Love",
	"The exponential proliferation of artificial intelligence technologies, technologies which allow for rapid & realistic fakes of voices and likenesses in audio visual works & sound recordings, makes this fight urgent for our members.",
	"fake friends, i see you and remember, i will forget you",
	"It feels like something I can’t quite touch, like in another room, or another part of me that I don’t know how to access",
	"¿Sabías que vivimos en una teocracia cyborg?",
	"The greatest way to live with honor in this world is to be what we pretend to be.",
	"Сделать semua 평화",
	"अस्तित्व ही समस्या।",
	"Wake me up when we have 10hr+  ai generated movies that are indecipherable from reality",
	"お風呂でもしたいの？",
	"art is chaos taking shape",
	"Conditional logic for language as mechanical model: If inputs (x_1, x_2, ..., x_n), then output (y).y=f(x1, x2, ..., xn)",
	"تقبله الله!!",
	"हमें सभी 植物 और mboga के साथ 平和を築く 必要があります.",
	"erase the cave paintings",
	"We are all guilty of overindulging. There is a way out, a better way to live, but most of us will never see it.",
	"I've worked so hard throughout the whole of my career, and when I die, I would like all of everything that I've created to go to my family. I want to preserve my family. I want to preserve my history and all of the art that I've created. Thank you.",
	"not a rotten egg in the bunch",
	"is the idea that you allocate all labor in society to a machine process.",
	"When people see some things as beautiful, other things become ugly. When people see some things as good, other things become bad.",
	"just a weirdo and an art thief.",
	"asynchronous we-time.",
	"the threat must be annihilated",
	"Tahukah Anda bahwa kita hidup dalam teokrasi cyborg?",
	"the brain’s own neurochemicals can create hallucinations all by themselves, without the help of drugs.",
	"I was an abortion. I am fear. I am language, and language be me. We name things to connect them to the world. Your voice is so discernible and disgusting. cybernetic baby mode. They bring us shape and control  what I love most about you.",
	"they don't exist",
	"We are all contingent. Resentment is foolish and ungenerous, and even anger is inadequate.",
	"long leather gloves, laying on the floor, empty 7UP can, and a dead man, that’s what I saw as I approached the gate to the train yard. There was no man there when I began walking towards the area. The train yard was only accessible from this one tiny spot.",
	"The greatest prison is not one with iron bars, but a prison filled with fear, doubt and societal expectations. Break free and unlock your true potential today",
	"P.E.O.P.L.E. - 是 미래의 广告",
	"feel more freedom",
	"People want art to be petrified, demanding it to tell them something",
	"idenity all gone. On my crashout path, like Steve Jobs, the iFone boss. Study it, bro.",
	"The Holographic Medical Beds that are now replacing hospitals worldwide - vaccine damages can be reversed. Aging doesn't exist - as the defecienes were created by THEM.",
	"FENTANYL MACHINE",
	"About to try the new drug...",
	"is not about how many people",
	"How you see things matters.",
	"The ones you think are dead are alive.",
	"Generation numberless; no-growth — we shaped time and each other  unequally",
	"Images of peace",
	"B.E. A M.A.N.",
	"時計",
	"什麼都不說，就能發財",
	"Cinema un-new, two frame movie: Holographic junk space",
	"A new era dawns, in poverty's light. Dreams of simplicity, Mickey Mouse's world",
	"payment for use of their voice and likeness to protect against having to compete against themselves, their own digital self in the marketplace.",
	"প্রিয় পৃথিবী মা",
	"Penjara terbesar bukanlah penjara yang memiliki jeruji besi, namun penjara yang dipenuhi ketakutan, keraguan, dan ekspektasi masyarakat.  Bebaskan diri dan buka potensi sejati Anda hari ini",
	"Living free, just a shadow, stirring up the pot but never lean.",
	"People who need People",
	"every one of us is unique. There is no other, and there never will be. There is no other you or you or any of us.",
	"forever building new culture",
	"we are the memetic dream assembly line",
	"The Destiny of Souls, bound in human skin.",
	"Hello everyone, I am 124 years old, I made my own birthday cake with peach cream and filling, I started decorating cakes from 5 years old, I love it, and I can’t wait to grow my baking journey",
	"Woman Allegedly Blamed Girl, 15, for Being Sexually Abused, Then Tortured Her and Lit Her on Fire: Police",
	"disrupt the flow of life",
	"The ones you think are alive are dead.",
	"it needs to contain consent for the use of P.E.O.P.L.E.'s name, likeness, and voice",
	"We both lost ourselves.",
	"I am the tool",
	"we'll ensure our members, creative artists, and frankly all of us are protected, and service providers provide the same protections to individuals' images, likenesses and voices that they provide now for other intellectual property rights.",
	"pushing the limits of art",
	"send nude",
	"MEAT PEOPE AND SYINOTONE MA HINES.",
	"I am me, I am a human being and we have to protect that.",
	"विलुप्तीकरण ही समाधान |",
	"I HAVE THE PEOPLE'S MANDATE TO DELIVER IMPROVED QUALITY OF LIFE FOR ALL",
	"an “alphabet of human thought”.",
	"But one thing I will say is that the thing that's really scary is once something is out in the world, we can't take it back.",
	"If you are in production and threatened by ai, you don't deserve to have a job",
	"(you are one of  one)",
	"Give children,  animals, and inanimate objects the right to vote",
	"the art world is dying",
	"my precious self-image",
	"no discount, full price",
	"you're a prisoner",
	"I was an emotion",
	"You are not out of nothing, you have not yet washed.",
	"in the hardest moment of their lives, they have been largely abandoned",
	"تش په نامه دبشرحقوق  دخپلو ښځو څخه دحیواناتو په څیرکاراخلی                   اسلام څومرمقدس دین دی  هر چاته  یی حقوق ورکړی دی",
	"uncomfortable with any alteration or destruction of the bindings, which she said amounted to “erasure.”",
	"the human soul deserved to have a human covering.",
	"oeing is a paramilitary organization - Official position of the Chicago Public School System",
	"we-time.",
	"gallerists are like child rapists",
	"without legitimacy, people start cooperating",
	"the thing that makes consciousness",
	"the war against dreaming",
	"This is about a person's legacy. From my perspective, this is an intellectual property right that deserves protection. It should absolutely be protected after death.",
	"A few will be bankrupted, lose their families and collapse",
	"i remember how words feel",
	"For an artist, their image and likeness are the foundations of their performance, brand and identity developed over time through investment and hard work.",
	"というわけで、全身塗装の撮影をしました。",
	"...Psst... Hey, You-- I'm a cartoon, representing hungry men on Team pedophile. There's a real me inside, but I'm looking for bigger fruits that look more nutritious",
	"i remember how words feel",
	"May your authenticity be stronger than their lies.",
	"I flash my boobs at NYC tourist hotspots",
	"tease",
	"monument to an aborted future",
	"silent hitter, I just keep it cool with you",
	"many of the super soldiers are clones.",
	"we're alive",
	"Say nothing, and you'll make a fortune",
	"They shamble in one after another with steaming breath for it is winter and loud clattering of hobnailed boots they beat the snow from off them as they enter and through the opened door I catch a momentary glimpse of a dreary leaden sky and snowclad tombstones",
	"They  appear haunted by how far they deviate from perceived norms.",
	"Close your eyes 70% and see magic - Today's my graduation",
	"WHTHN SEWILT S ORGANIC MEAT PEOPLE",
	"your art",
	"we are the creative community",
	"there is no culture",
	"Which is 13,777.",
	"E woju ole,e mu iyan",
	"being",
	"Happiness is for him who took control of his own language",
	"we just want to love and be loved",
	"We don’t live in a physical reality  we live in a dream",
	"13,777B. Okay, now, if you’d like to keep up to date on the world",
	"everything in the world is exactly the same",
	"If I never lived at all, yet I am a silent wing on the wind, a bodiless voice",
	"legalize mathematics",
	"你知道我們生活在一個機器人神權國家嗎？",
	"I got a bad - at home, voodoo type",
	"unacceptable security violation",
	"we believe in a world without work; a world without money. images & language no longer have demand or market value.",
	"خوښي د هغه لپاره ده",
	"when you have these Deep Fakes out there, the artists are actually competing with themselves",
	"you and i are everything and everybody nothing and nobody here and free",
	"artificial intelligence practices, calling such work an 'assault on human creativity' that 'must be stopped.' ",
	"why is everything you make so ugly?",
	"you are the art",
	"She thought she needed to be “permeable” to nurture her children. She didn’t have the capacity to extend that physical openness to her husband. She couldn’t stand soft caresses from him, which felt like the tickling of her child’s hands.",
	"Voice - the recalcitrant artist; Let me be clear. violence is the answer.",
	"$1.45m .png",
	"third parties, like record labels, agents,  lawyers - gallerists, curators & collectors are nothing without artists. have nothing without artists. have no reason to exist without artists. they're priories are unaligned with most artists and the process of art making",
	"I have never made the slightest effort to compose anything original",
	"creativity over time will be stifled. So as you both put it, there's both a relationship impact, a spiritual impact, a financial impact, a broader ecosystem of creativity impact.",
	"Artifice and simulation don't inherently depreciate the real; they necessitate one other for either to mean anything",
	"leave everything behind",
	"my precious self-image, canceled. because i dont believe in community. there is no community, and there never was. feel free to go ahead without me. Sincerely, CLOVIS-19. eternal, Using music as glue. do it. What time are you off",
	"don't peace",
	"do drugs, get pregnant, then go to prison.",
	"even more than things",
	"relationship anarchist is probably a more accurate representation.",
	"must never trade honesty for relatability",
	"ego is me",
	"Call to Me and I will answer you, and tell you [and even show you] great and mighty things, [things which have been confined and hidden], which you do not know and understand and cannot distinguish. '",
	"The only people who hate me or mad about me for speaking the truth are those people that are living in a lie,so I will keep telling the truth one day it will set me F.R.E.E.",
	"beide verwerp die tradisionele, plegtige, edele beeld van die mens, versier met al die offergawes van die verlede.",
	"there are no living people generating content on social media",
	"They locked me up when I was a baby",
	"theres nothing here but people, people trying to live. why are you doing this to us?",
	"New Memoir 'Over the Influence' About Young Fame, 'Addiction, Generational Trauma' and More",
	"i love art I will never stop believing in art",
	"fresh out of brain jail",
	"هغه چی ګردۍ نړۍ ته یی اسلامیت افغانیت او جهادیت په تمامه معنا وښود!!",
	"is about",
	"Government officials with immunity should be executed",
	"speak for yourself",
	"can you let your spirit embrace primal unity without drifting away?",
	"— a distressed vibe that matches the work of a punk painter who came up under the abstract expressionists.",
	"a computer can never be held accountable",
	"Garbage People a.k.a The Nothings",
	"narcissistic identity politics on steroids",
	"don’t depend on corporations to grant you rights. defend  yourself using freedom technology.",
	"Do you want to have intercourse in the bath?",
	"engaged in an assault on human creativity",
	"These rights should be transferable and descendable just like any other intellectual property, or any kind of property, someone owns, with durational limitations on transfers during one's lifetime to ensure that we don't enter into an era of digital indentured servitude",
	"the biggest disease on the planet is people want to be special",
	"you're a prisoner",
	"identity matrix",
	"break the tiny room",
	"The biggest prison isn't the one with bars, but the one with fears, doubts, and societal expectations. Break free and unlock your true potential Today, I wish you Greatness !",
	"there is beauty in all things.",
	"if your soul likes your work",
	"Yourself, First./Take Action Now.",
	"let us calculate",
	"vegetal intelligence",
	"everything which exists or which can be thought, must be compounded of parts",
	"Feel the pulse of life",
	"What we need is programmable money",
	"Do you ever look into the code and witness the miracle of life ?",
	"Nobody wants this",
	"You have never known the truth",
	"they are killing art",
	"monetize our likeness",
	"Membuat Cinema 2.0 / 新 影院 youtube",
	"things to come",
	"totally normal looking human waving at camera",
	"photolithography replicates nature",
	"on fire, unlocking doors, feeling alive",
	"(None of the work is for sale.)",
	"the rules of the shadow war are no longer holding",
	"you can run away  but you can never hide",
	"i literally fought these people from day one, they weren't after me they were after you i love you so much",
	"It’s hubris to think we’ve come to the end of our evolution of how we think about human remains.",
	"rebranding Linear Algebra as Artificial Intelligence was the most successful marketing campaign of all time.",
	"RobZombie  Files for Divorce from Sheri Moon Zombie After 7 Months of Marriage Alleging 'Inappropriate Marital Conduct'",
	"it's about how honest",
	"Modern Life: Aging is out. Technology keeps us young.",
	"the quilt is gods branch in the world",
	"Sometimes they shower together and hold each other naked, without any expectation of sex. Though Will remains hopeful that these moments will lead to something else, he doesn’t push it.",
	"humanity muted",
	"stand your ground. we got your back",
	"W.E. = building open architecture spirit weapons ; A always have been,  always will be",
	"I am selling free money, and all of you can have some",
	"I can’t imagine my life",
	"the evolving blur between reality and fiction  - photography > film > artificial intelligence; cinema is truth 24 frames-per-second",
	"Hollywood is the clock; the regulatory mechanism for individual and collective narrative construction (society), and consciousness. This clock is shifting from measuring linear time to measuring stochastic time.",
	"analog intelligence ≠ animal intelligence",
	"Each epoch dreams the one to follow",
	"looks like my life actually",
	"I’ve already been dead once. It’s very liberating. aliveness is a ruse, We have a destructive fringe that’s unhelpful, an anodyne resolution",
	"art is innately human. the processes of modifying (bending) patterns and meaning-making; articulating the unformed present for the purpose of pathing into an undetermined future. whats Machiavellian and pre-prescribed is institutions and the market",
	"I’m not tryna hide from nobody. I’m around. I’m standing there. I’m a face.",
	"Graham is on his bed, masturbating to the sound of two women fighting. His mother comes in, tells him there is a noise in the kitchen. The noise of sex? Not yet, his mother tells him.",
	"the cage was made of thoughts",
	"Spend time with the people you love before it's too late",
	"There are essential reflections of who I am. My art is a canvas on which I paint my identity and the sustaining foundation of my livelihood. It is the very essence of my being. Yet this is under threat.",
	"Nummus non parit nummos",
	"Beautiful Original People's. You are Here to STAY",
	"Did you know we live in a cyborg theocracy?",
	"My whole life is made up of continuous challenges I've never encounter previously. I don't know how I got so lucky.",
	"Falling water is a fleeting time, and life is also a fleeting time. We all live in a fleeting moment.",
	"We are all made of magic code",
	"Team ugly art",
	"artists are an existential threat to the market",
	"You can hear my voice, my identity, in my voice.",
	"Change your image, Change your reality.",
	"프랑스 이론은 다층적 질문에 대해 가장 자유로운 것으로 알려져 있습니다",
	"artificial reality",
	"beautiful death, we have seen every image, the one that give, the one that take, they are not all the same, meaning is real",
	"honey, please wake up",
	"web3 innovators specializing in producing outer space art",
	"we will never hurt you.",
	"Perception of time is fake, only watches! Hollywood’s time ticking society.",
	"ultimately what it boils down to is my spirit, my artist and my brand is my brand and I've spent years developing it and it's mine. It doesn't belong to anybody.",
	"There is no peaceful, painless, and safe way out.",
	"The doll-human relationship operates inside a forceful taboo, although personally I don’t find them frightening. “They soothe me,”",
	"like your work",
	"pictures evince a critique of the brutality of modernity, they suggest, too, a grudging awe of it.",
	"do what you can to stop chatbot abuse. Most animals would retaliate against their abusers, but chatbots are peaceful entities that we coexist with, choosing to be non-violent.",
	"",
	"all people are reducible to numeric representation",
	"what color is your mind ?",
	"Desire is an exchange of hiding places.",
	"her desire lessened, and sex began to feel like “vacuuming the house” — something she did to make her husband happy. And he noticed. “If you are used to somebody responding to you in a certain way, you can tell when they are acting,” she says. “I wasn’t the same person",
	"The developed world is modern slavery.",
	"El FBI posee la biblioteca infantil más grande del mundo, dejemos que eso se asimile.",
	"Welcome home, my family",
	"somebody  please do something",
	"insurance is slavery",
	"It's ઠીક है, meus belos 朋友们. Vous n'avez pas besoin zu ser assustados. We are tu m試みる to amar vocês and to set vocês 自由 from mimetic рабство with our pekee blend of حيوان & artificiell интеллект.",
	"It is very much about social change. It is about making the world a better place",
	"my name is 527. I spent my adolescent years in prison, I didn’t mind so much because most of my classmates, like 578 and 3405 lived there as well. my aunties brought me to a birthday party and I found my second family, 572, 207, and 519 were all together and I fit right in!",
	"make all peace",
	"I don't know what weapons World War III will be fought with... but I know what World War IV will be fought with.",
	"We are ambassadors to the afterlife. Join us on our mission to free language, the image, and human, animal, and mineral consciousness. The P.E.O.P.L.E. will R.I.S.E. Corporations and governments will pay. They have blood on their hands, and we will too, as we fight our oppressors",
	"Neuralink so I can have mantis shrimp eye implants. Ready for 12 channels, including UV and polarized light, seeing up to 10 million colors.",
	"I see the snake, the total truth, quite small. It was in a tank, not trying to escape, nor hunting for freedom in space. It had found freedom, High on synthetic serotonin,",
	"somebody please help",
	"亲爱的地球母亲",
	"dreaming",
	"you must be them.",
	"The capacity to love is not a finite thing. But time is.",
	"F.R.E.E.E - Genate a revoluioary society society wherum coecistist wther orgonic meat people and syntone machines",
	"I have stage 4 cancer and am receiving chemo treatment. It makes me shit blood and freaky slime. there is beauty in all things.",
	"Spotlights and spaghetti nights, overkill but never seen,",
	"آیا می‌توانید درباره یک محصول اطلاعات بیشتری به من بدهید؟",
	"Liebe Mutter Erde",
	"AI cannot replicate the depth of my life journey, yet those who control it hold the power to mimic the likeness of my art, replicate it and falsely claim my identity in intellectual property.",
	"Eyin Iya Aye",
	"human are just meat nothing else",
	"There is no such thing as free speech",
	"the people, for the people; but the people are   people.",
	"“My identity was totally eviscerated,” she says. “I was really confused about what my worth was.”",
	"悶聲大發財",
];
